version: '3.8'

services:
  front-end:
    build:
      context: ../../Part1/e1-14/
      dockerfile: Dockerfile_front
    ports:
      - "5000:5000"
  back-end:
    build:
      context: ../../Part1/e1-14/
      dockerfile: Dockerfile_back
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data