FROM node:16

EXPOSE 5000

RUN apt update && apt install git && git clone https://github.com/docker-hy/material-applications.git && mv /material-applications/example-frontend frontend && apt-get purge -y --auto-remove curl git && rm -rf /material-applications /var/lib/apt/lists/* && useradd -m appuser && chown -R appuser frontend /usr/local/

USER appuser

WORKDIR /frontend

RUN npm install && REACT_APP_BACKEND_URL=http://localhost:8080/ npm run build && npm install -g serve

CMD serve -s -l 5000 build
