FROM node:16-alpine

EXPOSE 5000

RUN apk update && apk add git && git clone https://github.com/docker-hy/material-applications.git && mv /material-applications/example-frontend frontend && rm -rf /material-applications /var/lib/apt/lists/* && adduser -D appuser && chown -R appuser frontend /usr/local/

USER appuser

WORKDIR /frontend

RUN npm install && REACT_APP_BACKEND_URL=http://localhost:8080/ npm run build && npm install -g serve

CMD serve -s -l 5000 build
