FROM golang:1.16-alpine

EXPOSE 8080

RUN apk update && apk add git && git clone https://github.com/docker-hy/material-applications.git && adduser -D appuser && chown -R appuser /go/material-applications/example-backend && cd /go/material-applications/example-backend && go build

USER appuser

WORKDIR /go/material-applications/example-backend

CMD REQUEST_ORIGIN=http://localhost:5000 ./server