version: '3.8'

services:
  front-end:
    build:
      dockerfile: Dockerfile_front
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api/
  back-end:
    build:
      dockerfile: Dockerfile_back
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - REQUEST_ORIGIN=http://localhost
  redis:
    image: redis
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db