# Changed: REACT_APP_BACKEND_URL, REQUEST_ORIGIN, (dockerfile locations)

version: '3.8'

services:
  front-end:
    build:
      dockerfile: Dockerfile_front
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api/
  back-end:
    build:
      dockerfile: Dockerfile_back
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - REQUEST_ORIGIN=http://localhost
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db